[package]
name = "uu_expr"
version = "0.0.3"
authors = ["uutils developers"]
license = "MIT"
description = "expr ~ (uutils) display the value of EXPRESSION"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/expr"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/expr.rs"

[dependencies]
libc = "0.2.42"
onig = { version = "6.0", default-features = false }
uucore = { version=">=0.0.6", package="uucore", path="../../uucore" }
uucore_procs = { version=">=0.0.5", package="uucore_procs", path="../../uucore_procs" }

[[bin]]
name = "expr"
path = "src/main.rs"

[profile.release]
lto = true
opt-level = 's'
